import Providers from '../Components/Providers/Providers'
import { Inter } from 'next/font/google'
import PageContainer from "@/Components/PageContainer"
import Navbar from '@/Components/Client/Navbar'
import { getUserToken } from '@/lib/utils'
import ClientPageContainer from "@/Components/Client/ClientPageContainer"
import "./globals.css"
import "../Components/Client/nav.css"
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode

}) {


  const userData = await getUserToken();

  return (
    <html lang="en" className='overflow-hidden'>
      <body className={inter.className}>
        <Providers>
          <ClientPageContainer userData={userData}>
            <PageContainer>
              <div className="page  bg-white h-[100vh] min-w-full flex justify-center overflow-hidden max-sm:flex-col ">
                <div className="c c1 w-[300px]  h-full max-sm:order-2 max-sm:w-full max-sm:h-[70px] overflow-hidden">
                  {userData && <Navbar />}
                </div>
                <div className="c c2 pl-4 flex w-[630px]  overflow-hidden h-[100%] grow max-sm:p-2 max-sm:pb-0 max-sm:w-full ">
                  {children}
                </div>
              </div>
            </PageContainer>
          </ClientPageContainer>
        </Providers>
      </body>
    </html>
  )
}
